# logging:
#   level:
#     org.springframework: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: pass
  # jpa:
  #   properties:
  #     javax:
  #       persistence:
  #         schema-generation:
  #           create-source: metadata
  #         scripts:
  #           action: create
  #           create-target: create.sql
  #   hibernate:
  #     ddl-auto: create